### ISSUE TITLE
Training configs about PeopleSnapshot dataset

### ISSUE THREAD

**Issue by XingyuRenSJTU** [zju3dv/neuralbody#8]
Hi Sida, @pengsida , Thanks for your great work! I had a problem re-training with your configuration on PeopleSnapshot dataset. There is no 'lib/evaluators/dtu/skinning.py' in the codes. Would you have a plan to release it?  Best : )

**Comment by pengsida** [comment]
Hi Xingyu,

I have updated the code.
Please inform me if there is any problem.

Best,
Sida

**Comment by Yamato-01** [comment]
Thanks for your help with my last problem! But I also meet this problem now. I search in the codes you updated, however, I can't find 'skinning.py' in 'lib/evaluators'. I also download the codes you released later to update previous codes but it still doesn't  work. Could you release the 'skinning.py' file?Thanks a lot!

**Comment by pengsida** [comment]
This code does not use `skinning.py`.
Please list the error message.

**Comment by Yamato-01** [comment]
When I run `python train_net.py --cfg_file configs/snapshot_f3c.yaml exp_name female3c resume False`, it failed with the error`FileNotFoundError: [Errno 2] No such file or directory: 'lib/evaluators/dtu/skinning.py'`.
